# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40e6cc6f645384da4400439b4940321e1686bdb2de4050227f292065c55e24daa3dbed72e0bf65bd0bda5de38ea49aef9387463d2fa15a5e0dc13f2c219c8439

test:
  secret_key_base: 6e8d089539b554a427daddb55539b3b3c3ad7f506e9acc25b2cf6167f7bf6f7a0dfd7748403b960e6817baf2ad39a2535e0429c76c084128d70cd10040dcdf98

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
